name: Build Header

on:
  push:
    branches:
      - main

jobs:
  build-header:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x generate-headers.sh

      - name: Run header build script
        run: ./generate-headers.sh

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add header.html
          git commit -m "Auto-update header [skip ci]" || echo "No changes to commit"
          git push
