name: Build Header

on:
  push:
    branches:
      - main

jobs:
  build-header:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run header build script
        shell: pwsh
        run: |
        ./build-header.ps1

      - name: Run header build script
        run: |
        chmod +x check-and-inject.sh
        ./check-and-inject.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ vars.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git add header.html
          git commit -m "Auto-update header [skip ci]" || echo "No changes to commit"
          git push
